databases:
  - name: dura-database
    databaseName: dura_7pfx
    user: dura_7pfx_user

services:
  - type: web
    name: dura-server
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dura-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
